site_name: My MkDocs Material Documentation
site_url: https://sitedocs1.com.br

repo_url: https://github.com/Projetos-de-Extensao/PBE_25.2_8002_I
repo_name: Repositório

theme:
  name: material
  palette:
    primary: black
    accent: white
  features: []

nav:
  - Integrantes do Grupo: index.md
  - Desenvolvimento:
      - Brainstorm: Desenvolvimento/Brainstorm.md
      - Mapa Mental: Desenvolvimento/mapa_mental.md
      - Fase Inicial: Desenvolvimento/fase inicial.md
      - RF/RNF: Desenvolvimento/RF_RNF.md
      - Casos de Uso: Desenvolvimento/casos_de_uso.md
      - Diagrama de Classes: Desenvolvimento/diagrama_de_classes.md
      - Protótipo Baixa Fidelidade: Desenvolvimento/prototipo_baixa_fidelidade.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.emoji

extra_css:
  - stylesheets/extra.css
